<a href="https://colab.research.google.com/github/wzy34/colab_projects/blob/main/Titanic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import pandas as pd
from torch.utils.data import Dataset, DataLoader, TensorDataset, random_split
import numpy as np

In [ ]:
import kagglehub

kagglehub.login()

VBox(children=(HTML(value='<center> <img\nsrc=https://www.kaggle.com/static/images/site-logo.png\nalt=\'Kaggle…

In [ ]:
import kagglehub

path = kagglehub.dataset_download("shuofxz/titanic-machine-learning-from-disaster")

print("Dataset path:", path)

Downloading to /root/.cache/kagglehub/datasets/shuofxz/titanic-machine-learning-from-disaster/1.archive...

100%|██████████| 33.1k/33.1k [00:00<00:00, 18.6MB/s]

Extracting files...
Dataset path: /root/.cache/kagglehub/datasets/shuofxz/titanic-machine-learning-from-disaster/versions/1

In [ ]:
import os

print(os.listdir(path))

['test.csv', 'train.csv']

In [ ]:
df = pd.read_csv(os.path.join(path, "train.csv"))
df.head(n = 40)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
12,13,0,3,"Saundercock, Mr. William Henry",male,20.0,0,0,A/5. 2151,8.0500,NaN,S
13,14,0,3,"Andersson, Mr. Anders Johan",male,39.0,1,5,347082,31.2750,NaN,S
14,15,0,3,"Vestrom, Miss. Hulda Amanda Adolfina",female,14.0,0,0,350406,7.8542,NaN,S
15,16,1,2,"Hewlett, Mrs. (Mary D Kingcome)",female,55.0,0,0,248706,16.0000,NaN,S
16,17,0,3,"Rice, Master. Eugene",male,2.0,4,1,382652,29.1250,NaN,Q
17,18,1,2,"Williams, Mr. Charles Eugene",male,NaN,0,0,244373,13.0000,NaN,S
18,19,0,3,"Vander Planke, Mrs. Julius (Emelia Maria Vande...",female,31.0,1,0,345763,18.0000,NaN,S
19,20,1,3,"Masselmani, Mrs. Fatima",female,NaN,0,0,2649,7.2250,NaN,C
20,21,0,2,"Fynney, Mr. Joseph J",male,35.0,0,0,239865,26.0000,NaN,S
21,22,1,2,"Beesley, Mr. Lawrence",male,34.0,0,0,248698,13.0000,D56,S
22,23,1,3,"McGowan, Miss. Anna ""Annie""",female,15.0,0,0,330923,8.0292,NaN,Q
23,24,1,1,"Sloper, Mr. William Thompson",male,28.0,0,0,113788,35.5000,A6,S
24,25,0,3,"Palsson, Miss. Torborg Danira",female,8.0,3,1,349909,21.0750,NaN,S
25,26,1,3,"Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...",female,38.0,1,5,347077,31.3875,NaN,S
26,27,0,3,"Emir, Mr. Farred Chehab",male,NaN,0,0,2631,7.2250,NaN,C
27,28,0,1,"Fortune, Mr. Charles Alexander",male,19.0,3,2,19950,263.0000,C23 C25 C27,S
28,29,1,3,"O'Dwyer, Miss. Ellen ""Nellie""",female,NaN,0,0,330959,7.8792,NaN,Q
29,30,0,3,"Todoroff, Mr. Lalio",male,NaN,0,0,349216,7.8958,NaN,S
30,31,0,1,"Uruchurtu, Don. Manuel E",male,40.0,0,0,PC 17601,27.7208,NaN,C
31,32,1,1,"Spencer, Mrs. William Augustus (Marie Eugenie)",female,NaN,1,0,PC 17569,146.5208,B78,C
32,33,1,3,"Glynn, Miss. Mary Agatha",female,NaN,0,0,335677,7.7500,NaN,Q
33,34,0,2,"Wheadon, Mr. Edward H",male,66.0,0,0,C.A. 24579,10.5000,NaN,S
34,35,0,1,"Meyer, Mr. Edgar Joseph",male,28.0,1,0,PC 17604,82.1708,NaN,C
35,36,0,1,"Holverson, Mr. Alexander Oskar",male,42.0,1,0,113789,52.0000,NaN,S
36,37,1,3,"Mamee, Mr. Hanna",male,NaN,0,0,2677,7.2292,NaN,C
37,38,0,3,"Cann, Mr. Ernest Charles",male,21.0,0,0,A./5. 2152,8.0500,NaN,S
38,39,0,3,"Vander Planke, Miss. Augusta Maria",female,18.0,2,0,345764,18.0000,NaN,S
39,40,1,3,"Nicola-Yarred, Miss. Jamila",female,14.0,1,0,2651,11.2417,NaN,C

In [ ]:
train_df = pd.read_csv(os.path.join(path, "train.csv"))
test_df = pd.read_csv(os.path.join(path, "test.csv"))

In [ ]:
train_df["Sex"] = train_df["Sex"].map({
    "male": 0,
    "female": 1
})

test_df["Sex"] = test_df["Sex"].map({
    "male": 0,
    "female": 1
})

In [ ]:
train_df = pd.get_dummies(
    train_df,
    columns=["Embarked"],
    dtype=float
)

test_df = pd.get_dummies(
    test_df,
    columns=["Embarked"],
    dtype=float
)

In [ ]:
train_df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked_C,Embarked_Q,Embarked_S
0,1,0,3,"Braund, Mr. Owen Harris",0,22.0,1,0,A/5 21171,7.2500,NaN,0.0,0.0,1.0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,38.0,1,0,PC 17599,71.2833,C85,1.0,0.0,0.0
2,3,1,3,"Heikkinen, Miss. Laina",1,26.0,0,0,STON/O2. 3101282,7.9250,NaN,0.0,0.0,1.0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,35.0,1,0,113803,53.1000,C123,0.0,0.0,1.0
4,5,0,3,"Allen, Mr. William Henry",0,35.0,0,0,373450,8.0500,NaN,0.0,0.0,1.0

In [ ]:
train_df["Age"] = train_df["Age"].fillna(train_df["Age"].median())
test_df["Age"] = test_df["Age"].fillna(train_df["Age"].median())

train_df["Fare"] = train_df["Fare"].fillna(train_df["Fare"].median())
test_df["Fare"] = test_df["Fare"].fillna(train_df["Fare"].median())

In [ ]:
features = [
    "Pclass",
    "Sex",
    "Age",
    "SibSp",
    "Parch",
    "Fare",
    "Embarked_C",
    "Embarked_Q",
    "Embarked_S"
]

X = train_df[features]
y = train_df["Survived"]
print(X.shape, y.shape)

(891, 9) (891,)

In [ ]:
X = torch.tensor(
    train_df[features].to_numpy(),
    dtype=torch.float32
)

y = torch.tensor(
    train_df["Survived"].to_numpy(),
    dtype=torch.float32
)
print(X.shape, y.shape)

dataset = TensorDataset(X, y)

torch.Size([891, 9]) torch.Size([891])

In [ ]:
train_size = int(0.8 * len(dataset))
val_size = len(dataset) - train_size

train_dataset, val_dataset = random_split(
    dataset,
    [train_size, val_size],
    generator=torch.Generator().manual_seed(42)
)

In [ ]:
train_loader = DataLoader(
    train_dataset,
    batch_size=32,
    shuffle=True
)

val_loader = DataLoader(
    val_dataset,
    batch_size=32,
    shuffle=False
)

In [ ]:
from torch import nn

class TitanicModel(nn.Module):
  def __init__(self):
    super().__init__()
    self.linear = nn.Sequential(
        nn.Linear(9, 16),
        nn.ReLU(),
        nn.Linear(16, 8),
        nn.ReLU(),
        nn.Linear(8, 1)
    )

  def forward(self, x):
    return self.linear(x).squeeze(-1)

In [ ]:
model = TitanicModel()

In [ ]:
loss_fn = nn.BCEWithLogitsLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=0.001)

In [ ]:
def train(dataloader, model, loss_fn, optimizer):
    size = len(dataloader.dataset)
    model.train()
    for batch, (X, y) in enumerate(dataloader):
        #X, y = X.to(device), y.to(device)

        # Compute prediction error
        pred = model(X)
        loss = loss_fn(pred, y)

        # Backpropagation
        loss.backward()
        optimizer.step()
        optimizer.zero_grad()

        if batch % 100 == 0:
            loss = loss.item()
            print(f"loss: {loss:>7f}")

In [ ]:
def test(dataloader, model, loss_fn):
    size = len(dataloader.dataset)
    num_batches = len(dataloader)
    model.eval()
    test_loss, correct = 0, 0
    with torch.no_grad():
        for X, y in dataloader:
            #X, y = X.to(device), y.to(device)
            pred = model(X)
            test_loss += loss_fn(pred, y).item()
            correct += ((pred >= 0).float() == y).float().sum().item()
    test_loss /= num_batches
    correct /= size
    print(f"Test Error: \n Accuracy: {(100*correct):>0.1f}%, Avg loss: {test_loss:>8f} \n")

In [ ]:
epochs = 100
for t in range(epochs):
    print(f"Epoch {t+1}\n-------------------------------")
    train(train_loader, model, loss_fn, optimizer)
    test(val_loader, model, loss_fn)

Epoch 1
-------------------------------
loss: 0.921810
Test Error:
 Accuracy: 61.5%, Avg loss: 0.690657

Epoch 2
-------------------------------
loss: 0.669095
Test Error:
 Accuracy: 70.9%, Avg loss: 0.644590

Epoch 3
-------------------------------
loss: 0.640430
Test Error:
 Accuracy: 68.2%, Avg loss: 0.632930

Epoch 4
-------------------------------
loss: 0.610530
Test Error:
 Accuracy: 67.6%, Avg loss: 0.618053

Epoch 5
-------------------------------
loss: 0.590859
Test Error:
 Accuracy: 68.7%, Avg loss: 0.614814

Epoch 6
-------------------------------
loss: 0.617794
Test Error:
 Accuracy: 69.3%, Avg loss: 0.608958

Epoch 7
-------------------------------
loss: 0.622623
Test Error:
 Accuracy: 68.7%, Avg loss: 0.606397

Epoch 8
-------------------------------
loss: 0.699782
Test Error:
 Accuracy: 68.7%, Avg loss: 0.602815

Epoch 9
-------------------------------
loss: 0.564145
Test Error:
 Accuracy: 69.8%, Avg loss: 0.596028

Epoch 10
-------------------------------
loss: 0.527154
Test Error:
 Accuracy: 68.7%, Avg loss: 0.596570

Epoch 11
-------------------------------
loss: 0.642402
Test Error:
 Accuracy: 69.3%, Avg loss: 0.598941

Epoch 12
-------------------------------
loss: 0.539666
Test Error:
 Accuracy: 68.2%, Avg loss: 0.594387

Epoch 13
-------------------------------
loss: 0.431512
Test Error:
 Accuracy: 68.7%, Avg loss: 0.591349

Epoch 14
-------------------------------
loss: 0.552297
Test Error:
 Accuracy: 68.7%, Avg loss: 0.596534

Epoch 15
-------------------------------
loss: 0.546337
Test Error:
 Accuracy: 69.3%, Avg loss: 0.588067

Epoch 16
-------------------------------
loss: 0.624114
Test Error:
 Accuracy: 69.8%, Avg loss: 0.586073

Epoch 17
-------------------------------
loss: 0.621767
Test Error:
 Accuracy: 69.8%, Avg loss: 0.588369

Epoch 18
-------------------------------
loss: 0.660094
Test Error:
 Accuracy: 70.4%, Avg loss: 0.587517

Epoch 19
-------------------------------
loss: 0.677188
Test Error:
 Accuracy: 71.5%, Avg loss: 0.579490

Epoch 20
-------------------------------
loss: 0.594853
Test Error:
 Accuracy: 70.9%, Avg loss: 0.578151

Epoch 21
-------------------------------
loss: 0.562825
Test Error:
 Accuracy: 71.5%, Avg loss: 0.573293

Epoch 22
-------------------------------
loss: 0.621306
Test Error:
 Accuracy: 70.9%, Avg loss: 0.564692

Epoch 23
-------------------------------
loss: 0.556334
Test Error:
 Accuracy: 70.9%, Avg loss: 0.566782

Epoch 24
-------------------------------
loss: 0.645411
Test Error:
 Accuracy: 71.5%, Avg loss: 0.559825

Epoch 25
-------------------------------
loss: 0.633672
Test Error:
 Accuracy: 70.9%, Avg loss: 0.557992

Epoch 26
-------------------------------
loss: 0.668328
Test Error:
 Accuracy: 70.4%, Avg loss: 0.558230

Epoch 27
-------------------------------
loss: 0.587188
Test Error:
 Accuracy: 69.3%, Avg loss: 0.554276

Epoch 28
-------------------------------
loss: 0.590194
Test Error:
 Accuracy: 69.3%, Avg loss: 0.552955

Epoch 29
-------------------------------
loss: 0.578370
Test Error:
 Accuracy: 71.5%, Avg loss: 0.538293

Epoch 30
-------------------------------
loss: 0.648892
Test Error:
 Accuracy: 70.9%, Avg loss: 0.542600

Epoch 31
-------------------------------
loss: 0.488003
Test Error:
 Accuracy: 74.3%, Avg loss: 0.518573

Epoch 32
-------------------------------
loss: 0.575352
Test Error:
 Accuracy: 69.8%, Avg loss: 0.534214

Epoch 33
-------------------------------
loss: 0.443980
Test Error:
 Accuracy: 73.7%, Avg loss: 0.510290

Epoch 34
-------------------------------
loss: 0.551941
Test Error:
 Accuracy: 71.5%, Avg loss: 0.511025

Epoch 35
-------------------------------
loss: 0.396477
Test Error:
 Accuracy: 71.5%, Avg loss: 0.507323

Epoch 36
-------------------------------
loss: 0.472032
Test Error:
 Accuracy: 75.4%, Avg loss: 0.489291

Epoch 37
-------------------------------
loss: 0.631589
Test Error:
 Accuracy: 74.3%, Avg loss: 0.486168

Epoch 38
-------------------------------
loss: 0.548886
Test Error:
 Accuracy: 74.3%, Avg loss: 0.488534

Epoch 39
-------------------------------
loss: 0.563819
Test Error:
 Accuracy: 73.2%, Avg loss: 0.481354

Epoch 40
-------------------------------
loss: 0.579075
Test Error:
 Accuracy: 79.3%, Avg loss: 0.465582

Epoch 41
-------------------------------
loss: 0.712201
Test Error:
 Accuracy: 73.7%, Avg loss: 0.474192

Epoch 42
-------------------------------
loss: 0.435528
Test Error:
 Accuracy: 75.4%, Avg loss: 0.467606

Epoch 43
-------------------------------
loss: 0.437712
Test Error:
 Accuracy: 77.1%, Avg loss: 0.455769

Epoch 44
-------------------------------
loss: 0.501343
Test Error:
 Accuracy: 76.5%, Avg loss: 0.483930

Epoch 45
-------------------------------
loss: 0.405600
Test Error:
 Accuracy: 77.7%, Avg loss: 0.464212

Epoch 46
-------------------------------
loss: 0.481894
Test Error:
 Accuracy: 79.9%, Avg loss: 0.450608

Epoch 47
-------------------------------
loss: 0.536884
Test Error:
 Accuracy: 77.7%, Avg loss: 0.465558

Epoch 48
-------------------------------
loss: 0.524557
Test Error:
 Accuracy: 81.0%, Avg loss: 0.439915

Epoch 49
-------------------------------
loss: 0.474537
Test Error:
 Accuracy: 81.6%, Avg loss: 0.441309

Epoch 50
-------------------------------
loss: 0.520176
Test Error:
 Accuracy: 80.4%, Avg loss: 0.445944

Epoch 51
-------------------------------
loss: 0.658942
Test Error:
 Accuracy: 83.2%, Avg loss: 0.427247

Epoch 52
-------------------------------
loss: 0.377191
Test Error:
 Accuracy: 81.0%, Avg loss: 0.435864

Epoch 53
-------------------------------
loss: 0.416654
Test Error:
 Accuracy: 81.6%, Avg loss: 0.438428

Epoch 54
-------------------------------
loss: 0.460482
Test Error:
 Accuracy: 83.2%, Avg loss: 0.422683

Epoch 55
-------------------------------
loss: 0.454701
Test Error:
 Accuracy: 82.7%, Avg loss: 0.419184

Epoch 56
-------------------------------
loss: 0.346534
Test Error:
 Accuracy: 82.7%, Avg loss: 0.422910

Epoch 57
-------------------------------
loss: 0.379490
Test Error:
 Accuracy: 82.7%, Avg loss: 0.418820

Epoch 58
-------------------------------
loss: 0.539794
Test Error:
 Accuracy: 82.7%, Avg loss: 0.418552

Epoch 59
-------------------------------
loss: 0.462984
Test Error:
 Accuracy: 82.1%, Avg loss: 0.422595

Epoch 60
-------------------------------
loss: 0.341666
Test Error:
 Accuracy: 78.8%, Avg loss: 0.440634

Epoch 61
-------------------------------
loss: 0.423420
Test Error:
 Accuracy: 81.6%, Avg loss: 0.431036

Epoch 62
-------------------------------
loss: 0.461060
Test Error:
 Accuracy: 84.4%, Avg loss: 0.411665

Epoch 63
-------------------------------
loss: 0.293930
Test Error:
 Accuracy: 83.2%, Avg loss: 0.418704

Epoch 64
-------------------------------
loss: 0.375513
Test Error:
 Accuracy: 83.2%, Avg loss: 0.417914

Epoch 65
-------------------------------
loss: 0.403623
Test Error:
 Accuracy: 78.2%, Avg loss: 0.457944

Epoch 66
-------------------------------
loss: 0.652617
Test Error:
 Accuracy: 82.1%, Avg loss: 0.432699

Epoch 67
-------------------------------
loss: 0.524450
Test Error:
 Accuracy: 79.9%, Avg loss: 0.438466

Epoch 68
-------------------------------
loss: 0.436140
Test Error:
 Accuracy: 83.2%, Avg loss: 0.419518

Epoch 69
-------------------------------
loss: 0.453190
Test Error:
 Accuracy: 81.6%, Avg loss: 0.431809

Epoch 70
-------------------------------
loss: 0.503728
Test Error:
 Accuracy: 79.3%, Avg loss: 0.436577

Epoch 71
-------------------------------
loss: 0.487352
Test Error:
 Accuracy: 83.2%, Avg loss: 0.415540

Epoch 72
-------------------------------
loss: 0.504100
Test Error:
 Accuracy: 83.8%, Avg loss: 0.412152

Epoch 73
-------------------------------
loss: 0.485438
Test Error:
 Accuracy: 79.3%, Avg loss: 0.436072

Epoch 74
-------------------------------
loss: 0.517172
Test Error:
 Accuracy: 83.8%, Avg loss: 0.415930

Epoch 75
-------------------------------
loss: 0.382298
Test Error:
 Accuracy: 82.7%, Avg loss: 0.418137

Epoch 76
-------------------------------
loss: 0.367939
Test Error:
 Accuracy: 78.2%, Avg loss: 0.443437

Epoch 77
-------------------------------
loss: 0.392579
Test Error:
 Accuracy: 84.4%, Avg loss: 0.409447

Epoch 78
-------------------------------
loss: 0.455619
Test Error:
 Accuracy: 82.7%, Avg loss: 0.427123

Epoch 79
-------------------------------
loss: 0.292086
Test Error:
 Accuracy: 83.2%, Avg loss: 0.420547

Epoch 80
-------------------------------
loss: 0.344740
Test Error:
 Accuracy: 82.7%, Avg loss: 0.425723

Epoch 81
-------------------------------
loss: 0.468864
Test Error:
 Accuracy: 80.4%, Avg loss: 0.433632

Epoch 82
-------------------------------
loss: 0.539007
Test Error:
 Accuracy: 84.4%, Avg loss: 0.415394

Epoch 83
-------------------------------
loss: 0.492154
Test Error:
 Accuracy: 84.4%, Avg loss: 0.417266

Epoch 84
-------------------------------
loss: 0.523949
Test Error:
 Accuracy: 79.3%, Avg loss: 0.433829

Epoch 85
-------------------------------
loss: 0.389028
Test Error:
 Accuracy: 79.3%, Avg loss: 0.435274

Epoch 86
-------------------------------
loss: 0.470354
Test Error:
 Accuracy: 79.3%, Avg loss: 0.439805

Epoch 87
-------------------------------
loss: 0.492693
Test Error:
 Accuracy: 79.9%, Avg loss: 0.434133

Epoch 88
-------------------------------
loss: 0.410390
Test Error:
 Accuracy: 82.7%, Avg loss: 0.426032

Epoch 89
-------------------------------
loss: 0.444987
Test Error:
 Accuracy: 82.7%, Avg loss: 0.423573

Epoch 90
-------------------------------
loss: 0.481416
Test Error:
 Accuracy: 79.3%, Avg loss: 0.430840

Epoch 91
-------------------------------
loss: 0.438655
Test Error:
 Accuracy: 79.3%, Avg loss: 0.439165

Epoch 92
-------------------------------
loss: 0.554012
Test Error:
 Accuracy: 79.3%, Avg loss: 0.442117

Epoch 93
-------------------------------
loss: 0.394284
Test Error:
 Accuracy: 84.4%, Avg loss: 0.415358

Epoch 94
-------------------------------
loss: 0.531692
Test Error:
 Accuracy: 84.4%, Avg loss: 0.419270

Epoch 95
-------------------------------
loss: 0.475058
Test Error:
 Accuracy: 82.1%, Avg loss: 0.428503

Epoch 96
-------------------------------
loss: 0.469963
Test Error:
 Accuracy: 84.9%, Avg loss: 0.409327

Epoch 97
-------------------------------
loss: 0.496450
Test Error:
 Accuracy: 83.2%, Avg loss: 0.423132

Epoch 98
-------------------------------
loss: 0.528664
Test Error:
 Accuracy: 84.4%, Avg loss: 0.420560

Epoch 99
-------------------------------
loss: 0.376560
Test Error:
 Accuracy: 84.4%, Avg loss: 0.410146

Epoch 100
-------------------------------
loss: 0.584565
Test Error:
 Accuracy: 85.5%, Avg loss: 0.411511

In [ ]:
test_loader = DataLoader(
    TensorDataset(
        torch.tensor(
            test_df[features].to_numpy(),
            dtype=torch.float32
        )
    ),
    batch_size=32,
    shuffle=False
)

In [ ]:
model.eval()

all_predictions = []

with torch.no_grad():
    for X_batch in test_loader:

        logits = model(X_batch[0])
        probabilities = torch.sigmoid(logits)

        predictions = (probabilities >= 0.5).int()

        all_predictions.append(predictions)

all_predictions = torch.cat(all_predictions)
print(all_predictions)

tensor([0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1,
        1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
        1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0,
        1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0,
        1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1,
        1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
        0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0,
        1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0,
        1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1,
        1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
        0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0,
        0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,
        0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1,
        0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1,
        0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0,
        1, 1, 1, 1, 1, 0, 1, 0, 0, 0], dtype=torch.int32)